name: 🐛 Bug report
description: Report a reproducible issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome 👋
        Thank you for taking the time to fill out a bug report 🙂

        The more information you provide, the easier & quicker it is for us to diagnose the problem.

        Please search the existing issues and recent releases to make sure your problem hasn't already been solved.
  - type: textarea
    id: summary
    attributes:
      label: Issue Summary
      description: Explain what's wrong
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Also tell us, what did you expect to happen?
      placeholder: |
        1. This is the first step...
        2. This is the second step, etc.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of `node-sqlite3` are you using?
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js Version
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: How did you install the library?
      description: Provide details of your operating system and architecture
    validations:
      required: true 
